const ActionTypes = {
    GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    Edit_CUSTOMER: "EDIT_CUSTOMER",
    GET_ALL_TRAINING: "GET_ALL_TRAINING",
    GET_CUSTOMER: "GET_CUSTOMER",
    USER_LOGIN: "USER_LOGIN",
    ADD_TRAINING: "ADD_TRAINING"
}
export default ActionTypes;
